### PR TITLE
Bug fix for phone number rendering

### LINKED ISSUE #372: Production Error: Category Government not functional
Client:
```Hello. While working in the guide today I tried to go to the category, government, and I get an error. Screen shot attached. I tried several other categories and they seem to work fine. ```

Screenshot was just the generic development error message.

### PR DESCRIPTION
**Pull request by williamowen65**
& a first step on refactoring to RendererHelper

I implemented a unit test and have 4 passing test. But I haven't viewed every page of phone numbers. I can see that it worked for the case of random 3 letters like (abc) for the test case I setup. 

closes #372

### CODE REVIEW

**Comment by williamowen65** [comment]
I created a new test project for that test case

File: PC2/Models/RendererHelper.cs [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        /// </summary>
+        /// <param name="complexPhoneNumber"></param>
+        /// <returns></returns>
+         public static string RenderPhone(string complexPhoneNumber)
+            {
+                if (string.IsNullOrWhiteSpace(complexPhoneNumber))
+                    return string.Empty;
+
+                // Regex for US phone numbers: (xxx) xxx-xxxx, xxx-xxx-xxxx, xxx.xxx.xxxx, xxx xxx xxxx
+                var phoneRegex = new Regex(@"\(?\d{3}\)?[\s\-.]?\d{3}[\s\-.]?\d{4}");
```
Comment (JoeProgrammer88) [inline PC2/Models/RendererHelper.cs:22]: Can we avoid var and use the [target-typed](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/new-operator#target-typed-new) syntax instead?

File: PC2/Program.cs [hunk 2]
```diff
@@ -23,6 +24,7 @@
 {
     options.Filters.Add<ApplicationInsightsPageViewTracker>();
 });
+builder.Services.AddScoped<RendererHelper>();
```
Comment (JoeProgrammer88) [inline PC2/Program.cs:27]: We can make the whole class static and avoid dependency injection with the `RendererHelper` since no state or settings are managed in the class

**Review by JoeProgrammer88 — CHANGES_REQUESTED** [review]
Awesome job! I left a couple small comments but the refactoring and functionality looks great overall! It looks like this fixes the current problem of having strings like (CRU) at the end of a phone number. One the small comments are addressed, I'll approve this and we can merge it

**Review by JoeProgrammer88 — APPROVED** [review]
